#! /usr/bin/env python
from time import sleep
import sys
import pyglet
from glob import glob
from pyglet.window import key
from sortedcontainers import SortedDict
window = pyglet.window.Window()
label = pyglet.text.Label('Hello, world',
                          font_name='Times New Roman',
                          font_size=36,
                          x=window.width//2, y=window.height//2,
                          anchor_x='center', anchor_y='center')

class menu:
	def __init__(self):
		pass
		self.mode = self.main
		self.pos  = -1
		self.items=[]
	def __call__(self):
		self.mode()
		self.pos = self.pos%len(self.items)
		for n,i in enumerate(self.items):
			if self.pos ==  n: i=i.upper()
			pyglet.text.Label(	i,
						font_size=36,
						x=window.width//2,
						y=window.height-(n+1)*window.height//(len(self.items)+5),
						anchor_x='center',#anchor_y='left'
					).draw()

	def main(self):
		self.items = SortedDict(
				{'start':self.start,
				'load':self.load,
				'exit':self.exit}
			)
	def start(self):
		self.items = SortedDict(
				{'campaign':self.campaign,
				 'sandbox':self.sandbox,
				 'back':self.main}
			)
	def load(self):
		pass
	def campaign(self):pass
	def sandbox(self):pass
	def exit(self):
		sys.exit()
	def up(self):
		self.pos -=1
	def down(self):
		self.pos +=1
	def enter(self):
		option = self.items.keys()[self.pos]
		self.mode = self.items[option]
		self.pos=-1

mode = 'menu'
m = menu()
@window.event
def on_draw():
	window.clear()
	if mode == 'menu':
		m()

@window.event
def on_key_press(symbol, modifiers):
	if symbol ==key.UP:
		m.up()
	if symbol ==key.DOWN:
		m.down()
	if symbol ==key.ENTER:
		m.enter()

pyglet.app.run()

